// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim":
            case "anim1":return [img`
................
......fffff.....
......fffff.....
......1ff1f.....
......fffff.....
...ff.fffff.....
...ff..fff......
...fffffffffff..
...fffffffffff..
......fffff.ff..
......fffff.ff..
......fffff.....
......fffff.....
......fffff.....
......fffff.....
......fffff.....
......fffff.....
......fffff.....
......fffff.....
......fffff.....
......fffff.....
......fffff.....
...ffffffff.....
...fffffffff....
..ff......ff....
..ff......ff....
..ff......ffff..
..ff......ffff..
...........fff..
................
`, img`
......fffff.....
......fffff.....
......1ff1f.....
......fffff.....
......fffff.....
.......fff......
...fffffffffff..
...fffffffffff..
...ff.fffff.ff..
...ff.fffff.ff..
......fffff.....
......fffff.....
......fffff.....
......fffff.....
......fffff.....
......fffff.....
......fffff.....
......fffff.....
......fffff.....
......fffff.....
......fffff.....
......fffff.....
......fffff.....
......fffff.....
......fffff.....
......fffff.....
......ff.ff.....
......ff.ff.....
......fffff.....
.....ffffff.....
`, img`
................
......fffff.....
......fffff.....
......1ff1f.....
......fffff.....
...ff.fffff.....
...ff..fff......
...fffffffffff..
...fffffffffff..
......fffff.ff..
......fffff.ff..
......fffff.....
......fffff.....
......fffff.....
......fffff.....
......fffff.....
......fffff.....
......fffff.....
......fffff.....
......fffff.....
.....ffffff.....
....ffffffff....
...ffffffffff...
..fff......ff...
..fff......ff...
..fff......ffff.
..fff......ffff.
..fff.......fff.
................
................
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
